version: 2.1

orbs:
  orb-tools: circleci/orb-tools@volatile

workflows:
  btd:
    jobs:
      - orb-tools/publish:
          orb-path: go-build/orb.yaml
          orb-ref: giantswarm/go-build@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true
