version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

workflows:
  catalog_build:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          artifact-path: catalog/orb.yml
          destination-orb-path: catalog/orb.yml
          source-dir: catalog
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: giantswarm/catalog
          orb-path: catalog/orb.yaml
          publish-token-variable: CIRCLECI_DEV_API_TOKEN
          requires:
            - orb-tools/pack

      - orb-tools/dev-promote-prod:
          orb-name: giantswarm/catalog
          publish-token-variable: CIRCLECI_DEV_API_TOKEN
          release: patch
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
